### ISSUE TITLE
Exemple doesn't work

### ISSUE THREAD

**Issue by jalbert33** [yorkshireinteractive/chartist-goal-line#5]
Download all project in zip
Unzip
Index doesn't show the chartist graphs. => TypeError: Chartist.plugins.ctBarLabels is not a function

When you open the js, we can see "Chartist.plugins.ctTargetLine" instead of "Chartist.plugins.ctBarLabels"

**Comment by OscarGodson** [comment]
OK I think I fixed the issue here. I removed the `index.html` file and updated the docs here https://github.com/yorkshireinteractive/chartist-goal-line (which updated the site here http://yorkshireinteractive.github.io/chartist-goal-line/)
